server {
    listen 80;

    # 1. Evita que o Nginx tente adivinhar a porta/protocolo nos redirecionamentos
    absolute_redirect off;

    # Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o Academic Service
    location /api/performance {
        proxy_pass http://if-performance-academic-service:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }

    location /api/classes {
        proxy_pass http://if-performance-academic-service:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }

    location /api/evaluations {
        proxy_pass http://if-performance-academic-service:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }

    location /api/courses {
        proxy_pass http://if-performance-academic-service:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }

    # Proxy para o Import and Report Service
    location /api/processing {
        proxy_pass http://if-performance-import-and-report-service:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }
}